package Hibernate;

// Generated 02-feb-2015 19:57:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Componente generated by hbm2java
 */
public class Componente implements java.io.Serializable {

	private Integer idComponente;
	private Subtipo subtipo;
	private String nombre;
	private Integer pvp;
	private Integer precioCoste;
	private Integer stock;
	private String descripcion;
	private Date fechaCompra;
	private Boolean estado;

	public Componente() {
	}

	public Componente(Subtipo subtipo, String nombre, Integer pvp,
			Integer precioCoste, Integer stock, String descripcion,
			Date fechaCompra, Boolean estado) {
		this.subtipo = subtipo;
		this.nombre = nombre;
		this.pvp = pvp;
		this.precioCoste = precioCoste;
		this.stock = stock;
		this.descripcion = descripcion;
		this.fechaCompra = fechaCompra;
		this.estado = estado;
	}

	public Integer getIdComponente() {
		return this.idComponente;
	}

	public void setIdComponente(Integer idComponente) {
		this.idComponente = idComponente;
	}

	public Subtipo getSubtipo() {
		return this.subtipo;
	}

	public void setSubtipo(Subtipo subtipo) {
		this.subtipo = subtipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getPvp() {
		return this.pvp;
	}

	public void setPvp(Integer pvp) {
		this.pvp = pvp;
	}

	public Integer getPrecioCoste() {
		return this.precioCoste;
	}

	public void setPrecioCoste(Integer precioCoste) {
		this.precioCoste = precioCoste;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

}
