package Hibernate;

// Generated 02-feb-2015 19:57:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo implements java.io.Serializable {

	private Integer idTipo;
	private String nombre;
	private Set<Subtipo> subtipos = new HashSet<Subtipo>(0);

	public Tipo() {
	}

	public Tipo(String nombre, Set<Subtipo> subtipos) {
		this.nombre = nombre;
		this.subtipos = subtipos;
	}

	public Integer getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Subtipo> getSubtipos() {
		return this.subtipos;
	}

	public void setSubtipos(Set<Subtipo> subtipos) {
		this.subtipos = subtipos;
	}

}
